export const lettuce = 'Lettuce'
export const cheese = 'Cheese'
export const meat = 'Meat'
export const bacon = 'Bacon'
export const tomato = 'Tomato'
export const onion = 'Onion'

export const coke = 'Coke'
export const sauce = 'Sauce'
export const frenchFries = 'FrenchFries'

export const firstName = 'First Name'
export const lastName = 'Last Name'
export const phoneNumber = 'Phone Number'
export const address = 'Your Address'
export const country = 'Country'
export const state = 'State'
export const city = 'City/District/Town'
export const pinCode = 'Pin Code'
export const addressType = 'Address Type'

export const dispatching = 'dispatching . . .'
export const onTheWay = 'on the way . . .'
export const delivered = 'delivered'