
export const philippinesStates = [
    'Agusan Del Norte',
    'Albay',
    'Batangas',
    'Benguet',
    'Cagayan',
    'Camarines Sur',
    'Capiz',
    'Cebu',
    'Davao Del Norte',
    'Davao Del Sur',
    'Dinagat Islands',
    'Ilocos Norte',
    'Ilocos Sur',
    'Iloilo',
    'Laguna',
    'Lanao Del Norte',
    'Leyte',
    'Manila',
    'Metropolitan Manila',
    'Misamis Occidental',
    'Misamis Oriental',
    'Negros Occidental',
    'Nueva Ecija',
    'Palawan', 
    'Pampanga', 
    'Pangasinan',
    'Samar', 
    'Shariff Kabunsuan',
    'South Cotabato', 
    'Tarlac', 
    'Zambales', 
    'Zamboanga Del Sur'
]

export const indianStates = [
    'Andaman & Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Ladakh',
    'Lakshadweep',	 
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',	
    'Odisha',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',	
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttarakhand',
    'Uttar Pradesh',
    'West Bengal'
]

